export const INCREASE_COUNT = "INCREASE_COUNT";
export const DECREASE_COUNT = "DECREASE_COUNT";
export const TOGGLEVISIBILITY = "TOGGLEVISIBILITY";
export const WHATCOLOR = "WHATCOLOR";
export const TODOINPUT = "TODOINPUT";
export const ADDTODO = "ADDTODO";
